name: 🐞 Bug
description: Found a bug? Something isn't working right? This is the issue for you!
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: 📝 Describe the Bug
      description: Describe the bug, and tell us what happened, and what you expected _should_ happen.
      placeholder: Tell us what happened!
      value: |
        **Bug Description**
        
        **Actual Behavior**
        
        **Expected Behavior**
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🪜 Reproducing the Bug
      description: If possible, include the steps to reproduce this bug here!
      placeholder: |
        1. ...
        2. ...
        3. ...
        4. See error...
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 📱 Device Environment
      description: |
        examples:
          - **Device**: iPhone 14 Pro
          - **iOS**: v16.4
          - **App Version**: v1.0.2
      value: |
          - Device:
          - iOS:
          - App Version:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: 💬 Additional Info
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
